# Generated by Django 4.1.3 on 2023-11-03 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("laboratory", "0002_alter_laboratory_options"),
        ("person", "0001_initial"),
        ("reserve", "0002_alter_reserve_options_reserve_laboratory"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserve",
            name="persons",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="person_reserves",
                to="person.person",
                verbose_name="Persona",
            ),
        ),
        migrations.AlterField(
            model_name="reserve",
            name="laboratory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="laboratory_reserve",
                to="laboratory.laboratory",
                verbose_name="Laboratorio",
            ),
        ),
    ]
