# Generated by Django 4.1.3 on 2023-11-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0001_initial"),
        ("reserve", "0003_reserve_persons_alter_reserve_laboratory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reserve",
            name="persons",
        ),
        migrations.AddField(
            model_name="reserve",
            name="person",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="person_reserve",
                to="person.person",
                verbose_name="Persona",
            ),
        ),
    ]
