# Generated by Django 4.1.3 on 2023-11-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0001_initial"),
        ("reserve", "0004_remove_reserve_persons_reserve_person"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserve",
            name="person",
            field=models.ManyToManyField(
                blank=True,
                related_name="person_reserve",
                to="person.person",
                verbose_name="Persona",
            ),
        ),
    ]
