# Generated by Django 4.1.3 on 2023-11-02 20:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("laboratory", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="laboratory",
            options={
                "verbose_name": 'Registro "Laboratorio"',
                "verbose_name_plural": 'Tabla de registros "Laboratorio"',
            },
        ),
    ]
